### PR TITLE
Fixed the wrong color of the options in the drop-down list in dark mode

### PR DESCRIPTION
**Pull request by pzhlkj6612**
Hi, please review and test my change.

OS:

- Ubuntu 18.04.5 (4.4.0-19041-Microsoft) (WSL) on Windows 10 2004 10.0.19041.508
- Ubuntu 20.04.1 (5.4.0-48-generic)

Dev env:

- node v14.13.0
- npm v6.14.8
- Live Server 5.6.1

Browsers:

- Windows 10 2004 64 bit [10.0.19041.508] (19041.1.amd64fre.vb_release.191206-1406)
  - Firefox 80.0.1/81.0 64 bit
  - Google Chrome 85.0.4183.121 64 bit
- Windows 7 SP1 64 bit [6.1.7061] (7601.24214.amd64fre.win7sp1_ldr_escrow.180801-1700)
  - Google Chrome 49.0.2623.112 64 bit

Screenshot:

screenshot_comparison

### CODE REVIEW

**Comment by magic-akari** [comment]
Hello, what's the browser version you are using?

**Comment by pzhlkj6612** [comment]
Oh sorry I forgot it.

Browsers:

- Firefox 80.0.1 64 bit
- Google Chrome 85.0.4183.121 64 bit

I tested it on your website ([https://lrc-maker.github.io/](https://lrc-maker.github.io/)) and locally.

**Comment by magic-akari** [comment]
LGTM.

Sorry for late response.

**Comment by pzhlkj6612** [comment]
It's OK.

Have a good vacation!

**Pull request merged**
